#!/bin/bash
# ════════════════════════════════════════════════════════════
#  runtime_security_setup.sh — Runtime Security Deployment (Falco + Tetragon)
#  Supported OS: Linux host (requires kernel >= 5.4 for eBPF)
#  Run as: root
#  Mode: Deployment template generation (does not install directly, outputs config files and deployment instructions)
#  Reference: falcosecurity/falco (CNCF graduated) + cilium/tetragon
#  Project home: https://github.com/0x10debug/vps-security-enhancement-scripts
# ════════════════════════════════════════════════════════════
#
# Usage:
#   sudo ./scripts/runtime_security_setup.sh                    # Interactive deployment wizard
#   sudo ./scripts/runtime_security_setup.sh --falco             # Generate Falco deployment config
#   sudo ./scripts/runtime_security_setup.sh --tetragon          # Generate Tetragon deployment config
#   sudo ./scripts/runtime_security_setup.sh --audit             # Read-only audit: check runtime security status
#   sudo ./scripts/runtime_security_setup.sh --rules             # List/manage detection rules
#   sudo ./scripts/runtime_security_setup.sh --output ./configs  # Specify config output directory
#
# Exit codes:
#   0 — Success
#   1 — Parameter error / kernel version not met
#   2 — Some features unavailable

set -euo pipefail

APP_NAME="runtime_security_setup"
APP_VER="v2.2.0"
MODE=""
OUTPUT_DIR=""
REPORT_DIR="/var/log/runtime-security"
TIMESTAMP=$(date +%Y%m%d%H%M%S)

C_FAIL='\033[0;31m'
C_OK='\033[0;32m'
C_WARN='\033[0;33m'
C_INFO='\033[0;34m'
C_RST='\033[0m'

# ── Parameter parsing ─────────────────────────────────────────────────
parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --falco) MODE="falco"; shift ;;
            --tetragon) MODE="tetragon"; shift ;;
            --audit) MODE="audit"; shift ;;
            --rules) MODE="rules"; shift ;;
            --output) OUTPUT_DIR="$2"; shift 2 ;;
            -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
            *) echo "Unknown parameter: $1"; exit 1 ;;
        esac
    done
    if [ -z "$MODE" ]; then
        MODE="interactive"
    fi
    if [ -z "$OUTPUT_DIR" ]; then
        OUTPUT_DIR="./runtime-security-configs"
    fi
}

# ── Kernel version check ─────────────────────────────────────────────
check_kernel_version() {
    local major minor
    major=$(uname -r | cut -d. -f1)
    minor=$(uname -r | cut -d. -f2)
    local ver_num=$((major * 100 + minor))
    if [ "$ver_num" -lt 504 ]; then
        echo -e "${C_FAIL}Kernel version $(uname -r) does not meet eBPF minimum requirement (>= 5.4)${C_RST}"
        echo -e "${C_INFO}Falco supports legacy mode (kernel module), Tetragon requires >= 5.4${C_RST}"
        return 2
    fi
    echo -e "${C_OK}Kernel version $(uname -r) meets eBPF requirement${C_RST}"
    return 0
}

# ── Check BTF support ────────────────────────────────────────────
check_btf() {
    if [ -f /sys/kernel/btf/vmlinux ]; then
        echo -e "${C_OK}BTF (BPF Type Format) available: /sys/kernel/btf/vmlinux${C_RST}"
        return 0
    else
        echo -e "${C_WARN}BTF not available, Falco/Tetragon requires BTF support or fallback config${C_RST}"
        return 1
    fi
}

# ── Falco config generation ───────────────────────────────────────────
generate_falco_config() {
    echo -e "${C_WARN}>>> Generate Falco deployment config <<<${C_RST}"
    mkdir -p "$OUTPUT_DIR/falco"

    # docker-compose.yml
    cat > "$OUTPUT_DIR/falco/compose.yml" <<'EOF'
# Falco Runtime Security — docker-compose template
# Generated by runtime_security_setup.sh
# Reference: https://falco.org/docs/getting-started/installation/

services:
  falco:
    image: falcosecurity/falco:0.39.0
    container_name: falco
    restart: unless-stopped
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      - ./falco.yaml:/etc/falco/falco.yaml:ro
      - ./rules:/etc/falco/rules.d:ro
      - falco-data:/var/lib/falco
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
    network_mode: host
    healthcheck:
      test: ["CMD", "falco", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  falco-data:
EOF

    # falco.yaml main config
    cat > "$OUTPUT_DIR/falco/falco.yaml" <<'EOF'
# Falco configuration — generated by runtime_security_setup.sh
# Reference: https://falco.org/docs/configuration/

# Driver type: modern_ebpf (requires kernel >= 5.4 + BTF) or legacy (kernel module)
driver:
  kind: modern_ebpf
  # For older kernels without BTF, use:
  # kind: modern_ebpf
  # buf_size_parsers: 8388608
  # buf_size_syscalls: 8388608

# Syscall buffer size (bytes)
syslog_buffer_size: 8388608

# Output formats
json_output: true
json_include_output_property: true
json_include_tags_property: true

# Outputs
stdout_output:
  enabled: true

syslog_output:
  enabled: true
  facility: local0
  priority: warning

file_output:
  enabled: true
  keep_alive: false
  filename: /var/log/falco/events.log

# HTTP output (for integration with alerting systems)
http_output:
  enabled: false
  url: "http://localhost:9200/falco"
  user_agent: "falco"

# Program output (execute command on alert)
program_output:
  enabled: false
  keep_alive: false
  program: "jq -cr '.' | curl -d @- http://localhost:9200/falco"

# Rule loading
rules_file:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml
  - /etc/falco/rules.d

# Priority threshold (emergency < alert < critical < error < warning < notice < informational < debug)
priority: debug

# Rate limiting
outputs:
  rate: 0
  max_burst: 0

# Base syscall isolation
base_syscalls:
  custom_set: []
  repair: false
EOF

    # Custom rules
    mkdir -p "$OUTPUT_DIR/falco/rules"
    cat > "$OUTPUT_DIR/falco/rules/vps-custom-rules.yaml" <<'EOF'
# Custom Falco rules for VPS security
# Generated by runtime_security_setup.sh

# Rule: Shell spawned in container
- rule: Shell Spawned in Container
  desc: A shell was spawned inside a container (potential container escape)
  condition: >
    evt.type = execve and container.id != host and
    (proc.name in (bash, sh, zsh, dash, ksh, fish) or
     proc.name in (nc, ncat, netcat, socat))
  output: >
    Shell spawned in container (user=%user.name container=%container.name
    image=%container.image.repository shell=%proc.name
    parent=%proc.pname cmdline=%proc.cmdline)
  priority: WARNING
  tags: [container, shell, mitre_execution]

# Rule: Read SSH key file
- rule: Read SSH Secret File
  desc: Attempt to read SSH private key file by non-ssh process
  condition: >
    open_read and fd.name contains '/.ssh/' and fd.name endswith 'id_rsa' and
    not proc.name in (ssh, scp, sftp, ssh-agent, sshd, git)
  output: >
    SSH key file read by unexpected process (user=%user.name proc=%proc.name
    file=%fd.name cmdline=%proc.cmdline container=%container.name)
  priority: WARNING
  tags: [filesystem, ssh, mitre_credential_access]

# Rule: Write below /etc
- rule: Write below /etc
  desc: Attempt to write to files below /etc (configuration tampering)
  condition: >
    open_write and fd.name startswith /etc/ and
    not proc.name in (apt, apt-get, dpkg, yum, dnf, rpm, systemd, dockerd,
                      containerd, kubelet, falco)
  output: >
    Write below /etc (user=%user.name proc=%proc.name file=%fd.name
    cmdline=%proc.cmdline container=%container.name)
  priority: ERROR
  tags: [filesystem, mitre_persistence]

# Rule: Crypto miner process
- rule: Crypto Miner Process
  desc: Detected potential crypto mining process
  condition: >
    evt.type = execve and
    (proc.name in (xmrig, stratum, minerd, cryptonight, cpuminer) or
     proc.cmdline contains "stratum+tcp" or proc.cmdline contains "xmrpool")
  output: >
    Crypto miner detected (user=%user.name proc=%proc.name
    cmdline=%proc.cmdline container=%container.name)
  priority: CRITICAL
  tags: [malware, cryptominer, mitre_execution]

# Rule: Reverse shell
- rule: Reverse Shell Connection
  desc: Detected potential reverse shell connection
  condition: >
    evt.type in (connect, sendto) and fd.typechar = 4 and
    (proc.name in (bash, sh, zsh, nc, ncat, socat, python, perl, ruby) and
     not fd.sip in (127.0.0.1, 0.0.0.0))
  output: >
    Reverse shell detected (user=%user.name proc=%proc.name
    dest=%fd.sip:%fd.sport cmdline=%proc.cmdline container=%container.name)
  priority: CRITICAL
  tags: [network, shell, mitre_exfiltration]
EOF

    # Deployment instructions
    cat > "$OUTPUT_DIR/falco/README.md" <<'EOF'
# Falco Runtime Security Deployment

## Prerequisites
- Linux kernel >= 5.4 (for eBPF driver)
- BTF support: check `/sys/kernel/btf/vmlinux` exists
- Docker

## Deployment

```bash
# 1. Review configuration
cat falco.yaml
cat rules/vps-custom-rules.yaml

# 2. Start Falco
docker compose -f compose.yml up -d

# 3. Verify
docker logs falco
docker exec falco falco --list-rules
```

## Integration

### With Loki/Promtail (log aggregation)
Falco JSON output → file → Promtail → Loki → Grafana

### With Alertmanager (alerting)
Enable `http_output` in falco.yaml to send events to a webhook receiver.

### With CrowdSec (response)
Falco CRITICAL alerts → webhook → CrowdSec bouncer → IP ban

## Custom Rules
Add custom rules to `rules/` directory. Falco auto-reloads on file change.

## Tuning
- Adjust `priority` threshold to reduce noise (warning = production, debug = troubleshooting)
- Use `outputs.rate` and `outputs.max_burst` for rate limiting
- Add exceptions to built-in rules in `falco_rules.local.yaml`
EOF

    echo -e "${C_OK}Falco config generated to: $OUTPUT_DIR/falco/${C_RST}"
    echo -e "${C_INFO}Files: compose.yml, falco.yaml, rules/vps-custom-rules.yaml, README.md${C_RST}"
}

# ── Tetragon config generation ────────────────────────────────────────
generate_tetragon_config() {
    echo -e "${C_WARN}>>> Generate Tetragon deployment config <<<${C_RST}"
    mkdir -p "$OUTPUT_DIR/tetragon"

    # docker-compose.yml (Tetragon runs as Docker container)
    cat > "$OUTPUT_DIR/tetragon/compose.yml" <<'EOF'
# Tetragon Runtime Security — docker-compose template
# Generated by runtime_security_setup.sh
# Reference: https://github.com/cilium/tetragon

services:
  tetragon:
    image: cilium/tetragon:v1.2.0
    container_name: tetragon
    restart: unless-stopped
    privileged: true
    pid: host
    cgroup: host
    volumes:
      - /sys/kernel/btf/vmlinux:/sys/kernel/btf/vmlinux:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys/fs/bpf:/sys/fs/bpf
      - ./policies:/etc/tetragon/policies:ro
      - tetragon-data:/var/lib/tetragon
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - BPF
      - PERFMON
    network_mode: host
    healthcheck:
      test: ["CMD", "tetragon", "version"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  tetragon-data:
EOF

    # Tetragon policy — container execution blocking
    mkdir -p "$OUTPUT_DIR/tetragon/policies"
    cat > "$OUTPUT_DIR/tetragon/policies/block-shell-in-container.yaml" <<'EOF'
# Tetragon TracingPolicy — Block shell execution in containers
# Generated by runtime_security_setup.sh
apiVersion: tetragon.io/v1alpha1
kind: TracingPolicy
metadata:
  name: block-shell-in-container
spec:
  tracepoints:
    - subsystem: syscalls
      event: sys_enter_execve
      args:
        - index: 0
          type: "string"
      selectors:
        - matchPIDs:
            - operator: In
              values:
                - pidNamespaceRoot # Only match container PID namespace
          matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/bin/bash"
                - "/bin/sh"
                - "/bin/zsh"
                - "/bin/dash"
                - "/usr/bin/bash"
                - "/usr/bin/sh"
          matchActions:
            - action: Sigkill
EOF

    # Tetragon policy — file integrity monitoring
    cat > "$OUTPUT_DIR/tetragon/policies/protect-etc.yaml" <<'EOF'
# Tetragon TracingPolicy — Protect /etc from unauthorized writes
# Generated by runtime_security_setup.sh
apiVersion: tetragon.io/v1alpha1
kind: TracingPolicy
metadata:
  name: protect-etc
spec:
  tracepoints:
    - subsystem: syscalls
      event: sys_enter_openat
      args:
        - index: 1
          type: "string"
      selectors:
        - matchArgs:
            - index: 1
              operator: "Prefix"
              values:
                - "/etc/"
          matchActions:
            - action: Post
              rateLimit: 1s
EOF

    # Tetragon policy — network connection monitoring
    cat > "$OUTPUT_DIR/tetragon/policies/monitor-network.yaml" <<'EOF'
# Tetragon TracingPolicy — Monitor outbound network connections from containers
# Generated by runtime_security_setup.sh
apiVersion: tetragon.io/v1alpha1
kind: TracingPolicy
metadata:
  name: monitor-network
spec:
  tracepoints:
    - subsystem: syscalls
      event: sys_enter_connect
      args:
        - index: 1
          type: "sockaddr"
      selectors:
        - matchPIDs:
            - operator: In
              values:
                - pidNamespaceRoot
          matchArgs:
            - index: 1
              operator: "DAddr"
              values:
                - "127.0.0.1"
                - "0.0.0.0"
          matchActions:
            - action: Post
              rateLimit: 5s
EOF

    # Deployment instructions
    cat > "$OUTPUT_DIR/tetragon/README.md" <<'EOF'
# Tetragon Runtime Security Deployment

## Prerequisites
- Linux kernel >= 5.4 (BTF required: `/sys/kernel/btf/vmlinux`)
- Docker
- eBPF support enabled

## Deployment

```bash
# 1. Check BTF
ls -la /sys/kernel/btf/vmlinux

# 2. Review policies
ls policies/
cat policies/block-shell-in-container.yaml

# 3. Start Tetragon
docker compose -f compose.yml up -d

# 4. Verify
docker logs tetragon
docker exec tetragon tetragon version
docker exec tetragon tetragon getevents
```

## Policies

### block-shell-in-container.yaml
Enforcement policy: kills any process that tries to spawn a shell inside a container.
Action: Sigkill (immediate termination).

### protect-etc.yaml
Monitoring policy: logs all write attempts to /etc/ directory.
Action: Post (log after event, no blocking).

### monitor-network.yaml
Monitoring policy: logs outbound network connections from containers (excluding localhost).
Action: Post with rate limiting (5s).

## Custom Policies
Add YAML policies to `policies/` directory. Tetragon auto-reloads.

## Falco vs Tetragon

| Dimension | Falco | Tetragon |
|---|---|---|
| Type | Detection (alerting) | Detection + Enforcement |
| Actions | Alert only | Sigkill, Kill, Post, Override |
| Rules format | YAML rules | Kubernetes TracingPolicy YAML |
| Community | CNCF graduated | Cilium project |
| Best for | Audit logging, alerting | Real-time enforcement, blocking |

## Integration
- Tetragon enforcement → immediate threat neutralization
- Falco detection → alerting pipeline → human review
- Combined: Tetragon blocks + Falco alerts = defense in depth
EOF

    echo -e "${C_OK}Tetragon config generated to: $OUTPUT_DIR/tetragon/${C_RST}"
    echo -e "${C_INFO}Files: compose.yml, policies/*.yaml, README.md${C_RST}"
}

# ── Read-only audit mode ─────────────────────────────────────────────
audit_runtime_security() {
    echo -e "${C_WARN}>>> Runtime security status audit <<<${C_RST}"
    echo -e "${C_INFO}Read-only mode, no configuration modified${C_RST}"
    echo ""

    if ! mkdir -p "$REPORT_DIR" 2>/dev/null; then
        REPORT_DIR="/tmp/runtime-security"
        mkdir -p "$REPORT_DIR" 2>/dev/null || true
    fi
    local report="$REPORT_DIR/runtime-audit-${TIMESTAMP}.txt"
    {
        echo "Runtime Security Audit Report"
        echo "=============================="
        echo "Date: $(date)"
        echo "Host: $(hostname 2>/dev/null || echo 'N/A')"
        echo "Kernel: $(uname -r)"
        echo "Script: $APP_NAME $APP_VER"
        echo ""
    } > "$report"

    # Kernel version
    echo -e "${C_INFO}── Kernel and eBPF support ──${C_RST}"
    local kernel_ok=0
    if check_kernel_version; then
        kernel_ok=1
        echo "Kernel: $(uname -r) — OK" >> "$report"
    else
        echo "Kernel: $(uname -r) — INSUFFICIENT (< 5.4)" >> "$report"
    fi

    # BTF
    local btf_ok=0
    if check_btf; then
        btf_ok=1
        echo "BTF: available" >> "$report"
    else
        echo "BTF: not available" >> "$report"
    fi

    # Falco status
    echo ""
    echo -e "${C_INFO}── Falco status ──${C_RST}"
    local falco_status="not installed"
    if command -v falco >/dev/null 2>&1; then
        falco_status="installed (host): $(falco --version 2>/dev/null | head -1)"
        echo -e "${C_OK}Falco Installed (host): $(falco --version 2>/dev/null | head -1)${C_RST}"
    elif docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^falco$"; then
        falco_status="running (container): $(docker exec falco falco --version 2>/dev/null | head -1 || echo 'version unknown')"
        echo -e "${C_OK}Falco container running${C_RST}"
    else
        echo -e "${C_WARN}Falco Not installed${C_RST}"
    fi
    echo "Falco: $falco_status" >> "$report"

    # Tetragon status
    echo ""
    echo -e "${C_INFO}── Tetragon status ──${C_RST}"
    local tetragon_status="not installed"
    if command -v tetragon >/dev/null 2>&1; then
        tetragon_status="installed (host): $(tetragon version 2>/dev/null | head -1)"
        echo -e "${C_OK}Tetragon Installed (host)${C_RST}"
    elif docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^tetragon$"; then
        tetragon_status="running (container)"
        echo -e "${C_OK}Tetragon container running${C_RST}"
    else
        echo -e "${C_WARN}Tetragon Not installed${C_RST}"
    fi
    echo "Tetragon: $tetragon_status" >> "$report"

    # eBPF program check
    echo ""
    echo -e "${C_INFO}── eBPF programs ──${C_RST}"
    local bpf_progs=0
    if [ -d /sys/fs/bpf ]; then
        bpf_progs=$(find /sys/fs/bpf -type f 2>/dev/null | wc -l || echo 0)
        bpf_progs=${bpf_progs:-0}
        echo -e "${C_INFO}BPF filesystem: /sys/fs/bpf ($bpf_progs objects)${C_RST}"
    else
        echo -e "${C_WARN}BPF filesystem not mounted${C_RST}"
    fi
    echo "BPF objects: $bpf_progs" >> "$report"

    # Recent Falco events
    if [ -f /var/log/falco/events.log ]; then
        echo ""
        echo -e "${C_INFO}── Recent Falco events (5) ──${C_RST}"
        local falco_events
        falco_events=$(tail -5 /var/log/falco/events.log 2>/dev/null || echo "Cannot read")
        echo "$falco_events"
        echo "" >> "$report"
        echo "Recent Falco events:" >> "$report"
        echo "$falco_events" >> "$report"
    fi

    # Container runtime security
    echo ""
    echo -e "${C_INFO}── Container runtime ──${C_RST}"
    if command -v docker >/dev/null 2>&1; then
        local running_containers
        running_containers=$(docker ps --format '{{.Names}}' 2>/dev/null | wc -l || echo 0)
        running_containers=${running_containers:-0}
        local privileged_containers
        privileged_containers=$(docker ps --format '{{.Names}} {{.Status}}' 2>/dev/null | grep -c "Privileged" || true)
        privileged_containers=${privileged_containers:-0}
        echo -e "${C_INFO}Running containers: $running_containers${C_RST}"
        echo -e "${C_INFO}Privileged containers: $privileged_containers${C_RST}"
        echo "Running containers: $running_containers" >> "$report"
        echo "Privileged containers: $privileged_containers" >> "$report"
    else
        echo -e "${C_WARN}Docker Not installed${C_RST}"
        echo "Docker: not installed" >> "$report"
    fi

    # Summary
    echo ""
    echo -e "${C_INFO}╔══════════════════════════════════════════╗${C_RST}"
    echo -e "${C_INFO}║  Runtime Security Audit Summary           ║${C_RST}"
    echo -e "${C_INFO}╚══════════════════════════════════════════╝${C_RST}"
    echo -e "Kernel eBPF: $([ "$kernel_ok" -eq 1 ] && echo -e "${C_OK}OK${C_RST}" || echo -e "${C_FAIL}INSUFFICIENT${C_RST}")"
    echo -e "BTF:         $([ "$btf_ok" -eq 1 ] && echo -e "${C_OK}available${C_RST}" || echo -e "${C_WARN}missing${C_RST}")"
    echo -e "Falco:       $([ "$falco_status" != "not installed" ] && echo -e "${C_OK}active${C_RST}" || echo -e "${C_WARN}not deployed${C_RST}")"
    echo -e "Tetragon:    $([ "$tetragon_status" != "not installed" ] && echo -e "${C_OK}active${C_RST}" || echo -e "${C_WARN}not deployed${C_RST}")"
    echo ""
    echo -e "Report: $report"
}

# ── Rule management ─────────────────────────────────────────────────
list_rules() {
    echo -e "${C_WARN}>>> Runtime security detection rules <<<${C_RST}"
    echo ""

    echo -e "${C_INFO}── Falco Custom rules (vps-custom-rules.yaml) ──${C_RST}"
    echo "  1. Shell Spawned in Container     [WARNING]  — Shell execution in container"
    echo "  2. Read SSH Secret File           [WARNING]  — SSH private key read"
    echo "  3. Write below /etc               [ERROR]    — Write to /etc directory"
    echo "  4. Crypto Miner Process           [CRITICAL] — Crypto miner"
    echo "  5. Reverse Shell Connection       [CRITICAL] — Reverse shell connection"
    echo ""

    echo -e "${C_INFO}── Tetragon policies ──${C_RST}"
    echo "  1. block-shell-in-container  [Sigkill]  — Block shell in container (enforce)"
    echo "  2. protect-etc               [Post]     — /etc write monitoring"
    echo "  3. monitor-network           [Post]     — Container outbound connection monitoring"
    echo ""

    echo -e "${C_INFO}── Falco built-in rules (partial) ──${C_RST}"
    echo "  - Terminal shell in container"
    echo "  - Contact cloud metadata service from container"
    echo "  - Container Drift (new executable created in container)"
    echo "  - Privileged container started"
    echo "  - User mgmt binaries run inside container"
    echo "  - Launch Suspicious Network Tool in Container"
    echo "  - Outbound or Inbound Traffic Not to Authorized Server"
    echo "  ... (100+ built-in rules)"
    echo ""
    echo -e "${C_INFO}View full built-in rules: docker exec falco falco --list-rules${C_RST}"
}

# ── Interactive mode ───────────────────────────────────────────────
interactive_mode() {
    echo -e "${C_INFO}╔══════════════════════════════════════════╗${C_RST}"
    echo -e "${C_INFO}║  Runtime Security Setup Wizard            ║${C_RST}"
    echo -e "${C_INFO}║  $APP_NAME $APP_VER                        ║${C_RST}"
    echo -e "${C_INFO}╚══════════════════════════════════════════╝${C_RST}"
    echo ""

    check_kernel_version || true
    check_btf || true
    echo ""

    echo -e "${C_INFO}Runtime security solution comparison:${C_RST}"
    echo ""
    echo -e "  ${C_WARN}1.${C_RST} Falco — detect+alert (CNCF graduated, 100+ built-in rules)"
    echo -e "  ${C_WARN}2.${C_RST} Tetragon — detect+enforce (eBPF real-time blocking)"
    echo -e "  ${C_WARN}3.${C_RST} Deploy both (Falco alert + Tetragon block = defense in depth)"
    echo -e "  ${C_WARN}4.${C_RST} Audit current status only (no config generated)"
    echo -e "  ${C_WARN}5.${C_RST} View detection rules"
    echo -e "  ${C_WARN}0.${C_RST} Exit"
    echo ""
    local pick
    read -r -p "Select [0-5]: " pick
    case $pick in
        1) generate_falco_config ;;
        2) generate_tetragon_config ;;
        3) generate_falco_config; echo ""; generate_tetragon_config ;;
        4) audit_runtime_security ;;
        5) list_rules ;;
        0) echo "Exit"; exit 0 ;;
        *) echo -e "${C_FAIL}Invalid input${C_RST}"; exit 1 ;;
    esac
}

# ── Main flow ───────────────────────────────────────────────────
main() {
    parse_args "$@"

    case "$MODE" in
        falco)
            check_kernel_version || true
            generate_falco_config
            ;;
        tetragon)
            check_kernel_version || true
            generate_tetragon_config
            ;;
        audit)
            audit_runtime_security || true
            ;;
        rules)
            list_rules
            ;;
        interactive)
            interactive_mode || true
            ;;
        *)
            echo "Unknown mode: $MODE"; exit 1
            ;;
    esac
    return 0
}

main "$@"
