#!/bin/bash
# ════════════════════════════════════════════════════════════
#  waf_setup.sh — Web Application Firewall (Coraza + OWASP CRS v4)
#  适用系统: Linux 主机
#  运行身份: root
#  模式: 部署 + 配置生成 + 审计 (不直接修改运行中的反代)
#  参考: corazawaf/coraza
#         zzmzm/tiyi
#         socfortress/waf-platform-public
#         OWASP Core Rule Set v4
#  项目主页: https://github.com/0x10debug/vps-security-enhancement-scripts
# ════════════════════════════════════════════════════════════
#
# 用法:
#   sudo ./scripts/waf_setup.sh                    # 交互式向导
#   sudo ./scripts/waf_setup.sh --install          # 安装 Coraza + CRS v4
#   sudo ./scripts/waf_setup.sh --caddy            # 生成 Caddy + Coraza 配置
#   sudo ./scripts/waf_setup.sh --nginx            # 生成 Nginx + Coraza 配置
#   sudo ./scripts/waf_setup.sh --haproxy          # 生成 HAProxy + Coraza 配置
#   sudo ./scripts/waf_setup.sh --tune             # 生成规则调优配置
#   sudo ./scripts/waf_setup.sh --audit            # 只读审计 WAF 配置
#   sudo ./scripts/waf_setup.sh --output ./waf-configs
#   sudo ./scripts/waf_setup.sh --domain waf.example.com
#
# 退出码:
#   0 — 成功
#   1 — 参数错误 / 依赖缺失
#   2 — 部分功能不可用

set -euo pipefail

APP_NAME="waf_setup"
APP_VER="v3.0.0"
MODE=""
OUTPUT_DIR=""
DOMAIN=""
REPORT_DIR="/var/log/waf-audit"
TIMESTAMP=$(date +%Y%m%d%H%M%S)

COUNT_PASS=0
COUNT_FAIL=0
COUNT_WARN=0
COUNT_SKIP=0
TOTAL_CHECKS=0

C_FAIL='\033[0;31m'
C_OK='\033[0;32m'
C_WARN='\033[0;33m'
C_INFO='\033[0;34m'
C_RST='\033[0m'

# ── 参数解析 ─────────────────────────────────────────────────
parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --install) MODE="install"; shift ;;
            --caddy) MODE="caddy"; shift ;;
            --nginx) MODE="nginx"; shift ;;
            --haproxy) MODE="haproxy"; shift ;;
            --tune) MODE="tune"; shift ;;
            --audit) MODE="audit"; shift ;;
            --output) OUTPUT_DIR="$2"; shift 2 ;;
            --domain) DOMAIN="$2"; shift 2 ;;
            -h|--help) sed -n '2,24p' "$0"; exit 0 ;;
            *) echo "未知参数: $1"; exit 1 ;;
        esac
    done
    if [ -z "$MODE" ]; then
        MODE="interactive"
    fi
    if [ -z "$OUTPUT_DIR" ]; then
        OUTPUT_DIR="./waf-configs"
    fi
    if [ -z "$DOMAIN" ]; then
        DOMAIN="waf.vps.local"
    fi
}

# ── 报告初始化 ───────────────────────────────────────────────
init_report() {
    mkdir -p "$REPORT_DIR" 2>/dev/null || REPORT_DIR="/tmp/waf-audit"
    mkdir -p "$REPORT_DIR" 2>/dev/null || true
    REPORT_FILE="$REPORT_DIR/waf-audit-${TIMESTAMP}.txt"
    {
        echo "WAF Security Audit Report"
        echo "==========================="
        echo "Date: $(date)"
        echo "Host: $(hostname 2>/dev/null || echo 'N/A')"
        echo "Script: $APP_NAME $APP_VER"
        echo ""
    } > "$REPORT_FILE"
}

# ── 检查函数 ─────────────────────────────────────────────────
run_check() {
    local id="$1" desc="$2"
    shift 2
    local result evidence rc

    evidence=$("$@" 2>&1) && rc=0 || rc=$?
    case $rc in
        0) result="PASS" ;;
        1) result="FAIL" ;;
        2) result="WARN" ;;
        *) result="SKIP" ;;
    esac

    TOTAL_CHECKS=$((TOTAL_CHECKS + 1))
    case "$result" in
        PASS) COUNT_PASS=$((COUNT_PASS + 1)) ;;
        FAIL) COUNT_FAIL=$((COUNT_FAIL + 1)) ;;
        WARN) COUNT_WARN=$((COUNT_WARN + 1)) ;;
        SKIP) COUNT_SKIP=$((COUNT_SKIP + 1)) ;;
    esac

    local color
    case "$result" in
        PASS) color="$C_OK" ;;
        FAIL) color="$C_FAIL" ;;
        WARN) color="$C_WARN" ;;
        SKIP) color="$C_INFO" ;;
    esac
    printf "  ${color}%-4s${C_RST} %s  %s\n" "$result" "$id" "$desc"

    {
        echo ""
        echo "[$result] $id $desc"
        echo "  Evidence: $evidence"
    } >> "$REPORT_FILE"
}

# ── Coraza + CRS 安装 ────────────────────────────────────────
install_coraza() {
    echo -e "${C_WARN}>>> 安装 Coraza WAF + OWASP CRS v4 <<<${C_RST}"
    mkdir -p "$OUTPUT_DIR/coraza"
    mkdir -p "$OUTPUT_DIR/crs"

    # 下载 OWASP CRS v4
    local crs_version="4.0.0"
    echo -e "${C_INFO}[1/3] 下载 OWASP CRS v${crs_version}...${C_RST}"
    curl -sL "https://github.com/coreruleset/coreruleset/archive/refs/tags/v${crs_version}.tar.gz" \
        -o /tmp/crs.tar.gz
    tar xzf /tmp/crs.tar.gz -C "$OUTPUT_DIR/crs/" --strip-components=1 2>/dev/null || {
        echo -e "${C_WARN}CRS 下载失败, 生成最小配置替代${C_RST}"
        mkdir -p "$OUTPUT_DIR/crs/rules"
        cat > "$OUTPUT_DIR/crs/crs-setup.conf" <<'EOF'
# OWASP CRS v4 — Minimal Setup (fallback)
# SecRuleEngine On
# SecDefaultAction "phase:1,pass,log,tag:'OWASP_CRS'"
EOF
    }
    rm -f /tmp/crs.tar.gz

    # 生成 Coraza 配置
    echo -e "${C_INFO}[2/3] 生成 Coraza 主配置...${C_RST}"
    cat > "$OUTPUT_DIR/coraza/coraza.conf" <<'EOF'
# Coraza WAF Configuration
# Generated by waf_setup.sh

# 启用 WAF 引擎
SecRuleEngine On

# 请求体限制
SecRequestBodyLimit 134217728
SecRequestBodyNoFilesLimit 1048576
SecRequestBodyInMemoryLimit 131072

# 响应体限制
SecResponseBodyLimit 524288

# 默认动作
SecDefaultAction "phase:1,pass,log,tag:'OWASP_CRS'"
SecDefaultAction "phase:2,pass,log,tag:'OWASP_CRS'"

# 包含 OWASP CRS
Include crs/crs-setup.conf
Include crs/rules/REQUEST-901-INITIALIZATION.conf
Include crs/rules/REQUEST-905-COMMON-PROTECTION.conf
Include crs/rules/REQUEST-911-METHOD-ENFORCEMENT.conf
Include crs/rules/REQUEST-913-SCANNER-DETECTION.conf
Include crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Include crs/rules/REQUEST-921-PROTOCOL-ATTACK.conf
Include crs/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
Include crs/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
Include crs/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Include crs/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
Include crs/rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
Include crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
Include crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Include crs/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
Include crs/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
Include crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf
Include crs/rules/RESPONSE-950-DATA-LEAKAGE.conf
Include crs/rules/RESPONSE-951-DATA-LEAKAGE-SQL.conf
Include crs/rules/RESPONSE-952-DATA-LEAKAGE-JAVA.conf
Include crs/rules/RESPONSE-953-DATA-LEAKAGE-PHP.conf
Include crs/rules/RESPONSE-954-DATA-LEAKAGE-IIS.conf
Include crs/rules/RESPONSE-959-BLOCKING-EVALUATION.conf

# 排除规则 (按需调整)
# Include crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf

# 日志配置
SecDebugLog /var/log/coraza/debug.log
SecDebugLogLevel 0
SecAuditEngine RelevantOnly
SecAuditLog /var/log/coraza/audit.log
SecAuditLogFormat JSON
SecAuditLogParts AFH
EOF

    # 生成 Dockerfile
    echo -e "${C_INFO}[3/3] 生成 Coraza Docker 部署文件...${C_RST}"
    cat > "$OUTPUT_DIR/coraza/Dockerfile" <<'EOF'
# Coraza WAF Docker Image
FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/corazawaf/coraza-spoa@latest

FROM alpine:3.20
RUN apk add --no-cache ca-certificates haproxy
COPY --from=builder /go/bin/coraza-spoa /usr/local/bin/coraza-spoa
COPY coraza.conf /etc/coraza/coraza.conf
COPY crs/ /etc/coraza/crs/
RUN mkdir -p /var/log/coraza
EXPOSE 9000
CMD ["coraza-spoa", "-config", "/etc/coraza/coraza.conf"]
EOF

    cat > "$OUTPUT_DIR/coraza/docker-compose.yml" <<EOF
# Coraza WAF Docker Compose
# Generated by waf_setup.sh
version: "3.8"
services:
  coraza:
    build: .
    container_name: coraza-waf
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./coraza.conf:/etc/coraza/coraza.conf:ro
      - ./crs:/etc/coraza/crs:ro
      - coraza-logs:/var/log/coraza
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  coraza-logs:
EOF

    cat > "$OUTPUT_DIR/coraza/README.md" <<'EOF'
# Coraza WAF Deployment

## Overview
Coraza is a Go-based WAF engine compatible with ModSecurity SecRules.
This setup uses Coraza as a SPOA (HAProxy Stream Processing Offload Agent)
with OWASP CRS v4 rules.

## Deployment
1. `cd coraza/`
2. `docker compose up -d`
3. Configure HAProxy to use Coraza SPOA (see haproxy config)

## Configuration
- `coraza.conf` — Main WAF configuration
- `crs/` — OWASP Core Rule Set v4
- `Dockerfile` — Coraza SPOA image
- `docker-compose.yml` — Docker deployment

## Verification
```bash
# Test SQL injection detection
curl -H "Host: $DOMAIN" "http://localhost/?id=1' OR '1'='1"
# Should be blocked with 403
```
EOF

    echo -e "${C_OK}Coraza + CRS v4 安装配置已生成到: $OUTPUT_DIR/coraza/${C_RST}"
}

# ── Caddy + Coraza 配置 ──────────────────────────────────────
generate_caddy_config() {
    echo -e "${C_WARN}>>> 生成 Caddy + Coraza 配置 <<<${C_RST}"
    mkdir -p "$OUTPUT_DIR/caddy"

    cat > "$OUTPUT_DIR/caddy/Caddyfile" <<EOF
# Caddy + Coraza WAF Configuration
# Generated by waf_setup.sh

{
    # 全局选项
    order coraza_waf before reverse_proxy
}

# WAF 站点
$DOMAIN {
    # Coraza WAF
    coraza_waf {
        directives `
            Include /etc/coraza/coraza.conf
        `
    }

    # 反向代理到后端
    reverse_proxy localhost:8080

    # 日志
    log {
        output file /var/log/caddy/waf-access.log
        format json
    }
}

# API 站点 (更严格规则)
api.$DOMAIN {
    coraza_waf {
        directives `
            Include /etc/coraza/coraza.conf
            SecRuleEngine On
        `
    }

    reverse_proxy localhost:3000
}
EOF

    cat > "$OUTPUT_DIR/caddy/docker-compose.yml" <<'EOF'
# Caddy + Coraza WAF Docker Compose
version: "3.8"
services:
  caddy:
    image: caddy:2.9.0-alpine
    container_name: caddy-waf
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - ../coraza:/etc/coraza:ro
      - caddy-logs:/var/log/caddy
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  caddy-data:
  caddy-config:
  caddy-logs:
EOF

    cat > "$OUTPUT_DIR/caddy/README.md" <<'EOF'
# Caddy + Coraza WAF

## Overview
Caddy v2.9 with Coraza WAF plugin. Automatic HTTPS + WAF protection.

## Deployment
1. Ensure Coraza configs are in ../coraza/
2. `docker compose up -d`
3. Caddy will auto-provision TLS certificates

## Configuration
- `Caddyfile` — Caddy config with coraza_waf directive
- `docker-compose.yml` — Docker deployment

## Notes
- Caddy's Coraza plugin uses caddy-coraza module
- For production, build a custom Caddy image with the plugin:
  ```bash
  xcaddy build --with github.com/corazawaf/coraza-caddy
  ```
EOF

    echo -e "${C_OK}Caddy + Coraza 配置已生成到: $OUTPUT_DIR/caddy/${C_RST}"
}

# ── Nginx + Coraza 配置 ──────────────────────────────────────
generate_nginx_config() {
    echo -e "${C_WARN}>>> 生成 Nginx + Coraza 配置 <<<${C_RST}"
    mkdir -p "$OUTPUT_DIR/nginx"

    cat > "$OUTPUT_DIR/nginx/nginx.conf" <<'EOF'
# Nginx + Coraza WAF Configuration
# Generated by waf_setup.sh

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format waf '$remote_addr - $remote_user [$time_local] '
                   '"$request" $status $body_bytes_sent '
                   '"$http_referer" "$http_user_agent" '
                   'waf_action=$coraza_action';

    access_log /var/log/nginx/waf-access.log waf;

    # Coraza SPOA 配置 (通过 stream 模块)
    # 需要 nginx-plus 或编译 coraza-nginx 模块

    upstream backend {
        server 127.0.0.1:8080;
    }

    server {
        listen 80;
        server_name _;

        # Coraza WAF (通过模块)
        # coraza on;
        # coraza_config_file /etc/coraza/coraza.conf;

        # 基础防护
        limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;
        limit_req zone=general burst=20 nodelay;

        # 阻止常见攻击
        if ($request_method !~ ^(GET|POST|PUT|DELETE|HEAD|OPTIONS|PATCH)$) {
            return 405;
        }

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 健康检查
        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }
}
EOF

    cat > "$OUTPUT_DIR/nginx/docker-compose.yml" <<'EOF'
# Nginx + Coraza WAF Docker Compose
# Note: Requires custom Nginx build with coraza-nginx module
version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-waf
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../coraza:/etc/coraza:ro
      - nginx-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  nginx-logs:
EOF

    cat > "$OUTPUT_DIR/nginx/Dockerfile" <<'EOF'
# Nginx with Coraza module
FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git gcc musl-dev
RUN go install github.com/corazawaf/coraza-nginx@latest

FROM nginx:1.27.2-alpine
COPY --from=builder /go/bin/coraza-nginx /usr/local/bin/coraza-nginx
# Note: This is a simplified Dockerfile.
# For production, you need to compile nginx with the coraza module.
EOF

    cat > "$OUTPUT_DIR/nginx/README.md" <<'EOF'
# Nginx + Coraza WAF

## Overview
Nginx with Coraza WAF module. Requires custom Nginx build.

## Deployment
1. Build custom Nginx with coraza-nginx module
2. `docker compose up -d`

## Configuration
- `nginx.conf` — Nginx config with Coraza directives
- `Dockerfile` — Custom Nginx build (simplified)
- `docker-compose.yml` — Docker deployment

## Notes
- Nginx Coraza integration requires module compilation
- For HAProxy, use the SPOA approach (see haproxy config)
- Consider using Caddy for easier Coraza integration
EOF

    echo -e "${C_OK}Nginx + Coraza 配置已生成到: $OUTPUT_DIR/nginx/${C_RST}"
}

# ── HAProxy + Coraza 配置 ────────────────────────────────────
generate_haproxy_config() {
    echo -e "${C_WARN}>>> 生成 HAProxy + Coraza SPOA 配置 <<<${C_RST}"
    mkdir -p "$OUTPUT_DIR/haproxy"

    cat > "$OUTPUT_DIR/haproxy/haproxy.cfg" <<'EOF'
# HAProxy + Coraza SPOA Configuration
# Generated by waf_setup.sh

global
    log stdout format raw local0
    maxconn 4096
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5s
    timeout client 50s
    timeout server 50s

# Coraza SPOA (Stream Processing Offload Agent)
backend coraza_spoa
    mode tcp
    server s1 127.0.0.1:9000

frontend waf_frontend
    bind *:80
    bind *:443 ssl crt /etc/haproxy/ssl/cert.pem alpn h2,http/1.1

    # Coraza WAF 检查
    filter spoe engine coraza config /etc/haproxy/coraza-spoa.cfg

    # 如果 WAF 拦截则返回 403
    http-request deny status 403 if { var(txn.coraza.action) -m str "denied" }

    # 速率限制
    http-request track-sc0 src table rate_limit
    http-request deny status 429 if { sc_http_req_rate(0) gt 100 }

    default_backend app_backend

backend app_backend
    balance roundrobin
    option httpchk GET /health
    server app1 127.0.0.1:8080 check

# 速率限制表
backend rate_limit
    stick-table type ip size 100k expire 30s store http_req_rate(10s)
EOF

    cat > "$OUTPUT_DIR/haproxy/coraza-spoa.cfg" <<'EOF'
# Coraza SPOA Configuration for HAProxy
# Generated by waf_setup.sh

[spos]
spoa-agent = coraza
spoa-server = 127.0.0.1:9000

[coraza]
# WAF 配置文件
config = /etc/coraza/coraza.conf

# 检查的请求部分
include = req_headers,req_body

# 检查的响应部分
include = res_headers,res_body
EOF

    cat > "$OUTPUT_DIR/haproxy/docker-compose.yml" <<'EOF'
# HAProxy + Coraza WAF Docker Compose
version: "3.8"
services:
  haproxy:
    image: haproxy:3.1.0-alpine
    container_name: haproxy-waf
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./coraza-spoa.cfg:/usr/local/etc/haproxy/coraza-spoa.cfg:ro
      - ../coraza:/etc/coraza:ro
      - haproxy-logs:/var/log/haproxy
    depends_on:
      - coraza
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 30s
      timeout: 5s
      retries: 3

  coraza:
    build:
      context: ../coraza
      dockerfile: Dockerfile
    container_name: coraza-spoa
    restart: unless-stopped
    volumes:
      - ../coraza/coraza.conf:/etc/coraza/coraza.conf:ro
      - ../coraza/crs:/etc/coraza/crs:ro

volumes:
  haproxy-logs:
EOF

    cat > "$OUTPUT_DIR/haproxy/README.md" <<'EOF'
# HAProxy + Coraza WAF

## Overview
HAProxy with Coraza SPOA (Stream Processing Offload Agent).
This is the recommended integration for production WAF deployment.

## Architecture
```
Client → HAProxy (443) → Coraza SPOA (9000) → Backend (8080)
```

## Deployment
1. Ensure Coraza configs are in ../coraza/
2. `docker compose up -d`
3. HAProxy will forward traffic through Coraza SPOA for inspection

## Configuration
- `haproxy.cfg` — HAProxy config with SPOA filter
- `coraza-spoa.cfg` — SPOA connection config
- `docker-compose.yml` — Docker deployment (HAProxy + Coraza)

## Advantages
- HAProxy SPOA is the native Coraza integration method
- High performance (Go SPOA process)
- Non-blocking inspection
EOF

    echo -e "${C_OK}HAProxy + Coraza 配置已生成到: $OUTPUT_DIR/haproxy/${C_RST}"
}

# ── 规则调优配置 ─────────────────────────────────────────────
generate_tuning_config() {
    echo -e "${C_WARN}>>> 生成 WAF 规则调优配置 <<<${C_RST}"
    mkdir -p "$OUTPUT_DIR/tuning"

    cat > "$OUTPUT_DIR/tuning/crs-setup.conf" <<'EOF'
# OWASP CRS v4 Tuning Configuration
# Generated by waf_setup.sh
#
# This file contains tuning parameters to reduce false positives
# while maintaining strong security posture.

# ── 异常评分阈值 ──
# 默认 5 (入站) / 4 (出站)
# 降低 = 更宽松, 升高 = 更严格
SecAction "id:900100,phase:1,pass,nolog,setvar:tx.inbound_anomaly_score_threshold=5"
SecAction "id:900101,phase:1,pass,nolog,setvar:tx.outbound_anomaly_score_threshold=4"

# ── 并发检测 ──
# 多个规则同时触发时合并评分
SecAction "id:900110,phase:1,pass,nolog,setvar:tx.paranoia_level=1"

# ── 方法白名单 ──
# 允许的方法: GET, POST, PUT, DELETE, HEAD, OPTIONS, PATCH
SecAction "id:900200,phase:1,pass,nolog,setvar:tx.allowed_methods='GET HEAD POST OPTIONS PUT DELETE PATCH'"

# ── 内容类型白名单 ──
SecAction "id:900220,phase:1,pass,nolog,setvar:tx.allowed_content_types='application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/json|charset=utf-8'"

# ── 排除规则 (减少误报) ──
# 排除特定参数的 SQL 注入检查 (适用于 API)
# SecRuleUpdateTarget 942100 "!ARGS:api_key"
# SecRuleUpdateTarget 942100 "!ARGS:search_query"

# 排除特定路径的 XSS 检查 (适用于富文本编辑器)
# SecRuleUpdateTarget 941100 "!ARGS:content"
# SecRuleUpdateTarget 941100 "!ARGS:description"

# ── 地理位置限制 ──
# 需要安装 MaxMind GeoIP2
# SecGeoLookupDb /etc/geoip/GeoLite2-City.mmdb
# SecRule REMOTE_ADDR "@geoLookup" "chain,id:900700,phase:1,deny,status:403"
#     SecRule GEO:COUNTRY_CODE "!@in US CA GB DE JP" "msg:'Blocked by GeoIP'"

# ── 速率限制 ──
# 通过 Coraza 的 rate limiting
# SecAction "id:900800,phase:1,pass,nolog,setvar:tx.rate_limit=100"

# ── 日志级别 ──
# 生产环境建议: 0 (只记录拦截)
# 调试环境建议: 3 (详细日志)
SecDebugLogLevel 0
EOF

    cat > "$OUTPUT_DIR/tuning/false-positive-handling.md" <<'EOF'
# WAF False Positive Handling Guide

## Overview
False positives (FP) are legitimate requests blocked by WAF rules.
This guide helps identify and resolve FPs without compromising security.

## Step 1: Identify False Positives
Monitor the Coraza audit log:
```bash
tail -f /var/log/coraza/audit.log | jq '.transaction.request.uri, .rules[].msg'
```

## Step 2: Analyze the Rule
Each blocked request includes:
- Rule ID (e.g., 942100 = SQL Injection)
- Matched data (which parameter triggered)
- Rule message

## Step 3: Create Exclusion
For legitimate requests that trigger rules, create targeted exclusions:

### Exclude specific parameter from a rule:
```apache
SecRuleUpdateTarget 942100 "!ARGS:search_query"
```

### Exclude specific parameter from all rules:
```apache
SecRuleRemoveById 942100 "ARGS:search_query"
```

### Exclude specific URL from a rule:
```apache
SecRuleRemoveById 942100 "REQUEST_URI:/api/search"
```

## Step 4: Adjust Paranoia Level
- PL1: Default, minimal FP
- PL2: More rules, some FP
- PL3: Aggressive, more FP
- PL4: Paranoid, many FP

```apache
SecAction "id:900110,phase:1,pass,nolog,setvar:tx.paranoia_level=1"
```

## Step 5: Use Anomaly Scoring
Instead of blocking on first match, use anomaly scoring:
- Each rule adds points to a score
- Request is blocked only if total score exceeds threshold
- This allows legitimate requests with minor matches to pass

## Common False Positives
| Rule | Common FP Cause | Fix |
|------|----------------|-----|
| 942100 (SQLi) | Search queries with SQL keywords | Exclude search parameter |
| 941100 (XSS) | Rich text editors with HTML | Exclude content parameter |
| 920300 (Protocol) | APIs with custom headers | Add header to allowed list |
| 932100 (RCE) | Shell-like commands in text | Exclude specific parameter |

## Testing After Changes
```bash
# Test legitimate request passes
curl "https://$DOMAIN/search?q=normal+query"
# Test attack is still blocked
curl "https://$DOMAIN/?id=1' OR '1'='1"
```
EOF

    cat > "$OUTPUT_DIR/tuning/README.md" <<'EOF'
# WAF Rule Tuning

## Overview
Tuning configuration for OWASP CRS v4 to balance security and usability.

## Files
- `crs-setup.conf` — CRS tuning parameters (anomaly scoring, paranoia level, exclusions)
- `false-positive-handling.md` — Guide for identifying and resolving false positives

## Key Parameters
- **inbound_anomaly_score_threshold**: 5 (default), lower = more permissive
- **paranoia_level**: 1 (default), higher = more rules but more FPs
- **allowed_methods**: HTTP methods that bypass method enforcement
- **allowed_content_types**: Content types that bypass content type checks

## Deployment
1. Copy crs-setup.conf to /etc/coraza/crs/crs-setup.conf
2. Restart Coraza: `docker restart coraza-spoa`
3. Monitor for false positives
4. Adjust exclusions as needed
EOF

    echo -e "${C_OK}规则调优配置已生成到: $OUTPUT_DIR/tuning/${C_RST}"
}

# ── 审计模式 ─────────────────────────────────────────────────
audit_waf() {
    echo -e "${C_WARN}>>> WAF 安全审计 <<<${C_RST}"
    echo -e "${C_INFO}只读模式, 不修改任何配置${C_RST}"
    echo ""

    init_report

    echo -e "${C_INFO}── Coraza 安装检查 ──${C_RST}"

    run_check "WAF-1.1" "Coraza 配置文件存在" \
        bash -c "find /etc/coraza /etc/nginx /etc/caddy /etc/haproxy -name 'coraza*' -o -name '*waf*' 2>/dev/null | head -1 | grep -q . && echo 'config found' && return 0 || echo 'no WAF config found' && return 2"

    run_check "WAF-1.2" "OWASP CRS 规则目录存在" \
        bash -c "find /etc/coraza /opt/coraza -name 'crs' -type d 2>/dev/null | head -1 | grep -q . && echo 'CRS directory found' && return 0 || echo 'CRS directory not found' && return 2"

    run_check "WAF-1.3" "CRS v4 规则文件存在" \
        bash -c "find / -path '*/crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf' 2>/dev/null | head -1 | grep -q . && echo 'CRS v4 SQLi rule found' && return 0 || echo 'CRS v4 rules not found' && return 2"

    echo ""
    echo -e "${C_INFO}── WAF 引擎状态 ──${C_RST}"

    run_check "WAF-2.1" "Coraza SPOA 容器运行中" \
        bash -c "docker ps --format '{{.Names}}' 2>/dev/null | grep -qi coraza && echo 'coraza container running' && return 0 || echo 'coraza container not running' && return 2"

    run_check "WAF-2.2" "WAF 引擎已启用 (SecRuleEngine On)" \
        bash -c "find /etc/coraza -name '*.conf' -exec grep -l 'SecRuleEngine On' {} \; 2>/dev/null | head -1 | grep -q . && echo 'WAF engine enabled' && return 0 || echo 'WAF engine may be disabled' && return 2"

    run_check "WAF-2.3" "请求体大小限制已配置" \
        bash -c "find /etc/coraza -name '*.conf' -exec grep -l 'SecRequestBodyLimit' {} \; 2>/dev/null | head -1 | grep -q . && echo 'request body limit configured' && return 0 || echo 'request body limit not configured' && return 2"

    echo ""
    echo -e "${C_INFO}── 反代集成检查 ──${C_RST}"

    run_check "WAF-3.1" "HAProxy SPOA 集成已配置" \
        bash -c "grep -q 'coraza_spoa\|filter spoe' /etc/haproxy/haproxy.cfg 2>/dev/null && echo 'HAProxy SPOA configured' && return 0 || echo 'HAProxy SPOA not configured' && return 2"

    run_check "WAF-3.2" "Caddy Coraza 插件已配置" \
        bash -c "grep -q 'coraza_waf' /etc/caddy/Caddyfile 2>/dev/null && echo 'Caddy Coraza configured' && return 0 || echo 'Caddy Coraza not configured' && return 2"

    run_check "WAF-3.3" "Nginx Coraza 模块已配置" \
        bash -c "grep -q 'coraza' /etc/nginx/nginx.conf 2>/dev/null && echo 'Nginx Coraza configured' && return 0 || echo 'Nginx Coraza not configured' && return 2"

    echo ""
    echo -e "${C_INFO}── 规则配置检查 ──${C_RST}"

    run_check "WAF-4.1" "异常评分模式已启用" \
        bash -c "find /etc/coraza -name '*.conf' -exec grep -l 'inbound_anomaly_score_threshold' {} \; 2>/dev/null | head -1 | grep -q . && echo 'anomaly scoring enabled' && return 0 || echo 'anomaly scoring not configured' && return 2"

    run_check "WAF-4.2" "SQL 注入防护规则已加载" \
        bash -c "find / -path '*/crs/rules/REQUEST-942-*.conf' 2>/dev/null | head -1 | grep -q . && echo 'SQLi rules loaded' && return 0 || echo 'SQLi rules not found' && return 2"

    run_check "WAF-4.3" "XSS 防护规则已加载" \
        bash -c "find / -path '*/crs/rules/REQUEST-941-*.conf' 2>/dev/null | head -1 | grep -q . && echo 'XSS rules loaded' && return 0 || echo 'XSS rules not found' && return 2"

    run_check "WAF-4.4" "RCE 防护规则已加载" \
        bash -c "find / -path '*/crs/rules/REQUEST-932-*.conf' 2>/dev/null | head -1 | grep -q . && echo 'RCE rules loaded' && return 0 || echo 'RCE rules not found' && return 2"

    echo ""
    echo -e "${C_INFO}── 日志与监控 ──${C_RST}"

    run_check "WAF-5.1" "审计日志已配置" \
        bash -c "find /etc/coraza -name '*.conf' -exec grep -l 'SecAuditLog' {} \; 2>/dev/null | head -1 | grep -q . && echo 'audit log configured' && return 0 || echo 'audit log not configured' && return 2"

    run_check "WAF-5.2" "审计日志文件存在" \
        bash -c "find /var/log/coraza -name 'audit.log' 2>/dev/null | head -1 | grep -q . && echo 'audit log exists' && return 0 || echo 'audit log not found' && return 2"

    # 摘要
    echo ""
    echo -e "${C_INFO}╔══════════════════════════════════════════╗${C_RST}"
    echo -e "${C_INFO}║  WAF Audit Summary                         ║${C_RST}"
    echo -e "${C_INFO}╚══════════════════════════════════════════╝${C_RST}"
    echo ""
    printf "  ${C_OK}PASS${C_RST}: %d\n" "$COUNT_PASS"
    printf "  ${C_FAIL}FAIL${C_RST}: %d\n" "$COUNT_FAIL"
    printf "  ${C_WARN}WARN${C_RST}: %d\n" "$COUNT_WARN"
    printf "  ${C_INFO}SKIP${C_RST}: %d\n" "$COUNT_SKIP"
    printf "  Total: %d\n" "$TOTAL_CHECKS"
    echo ""
    echo -e "报告: $REPORT_FILE"
}

# ── 交互式模式 ───────────────────────────────────────────────
interactive_mode() {
    echo -e "${C_INFO}╔══════════════════════════════════════════╗${C_RST}"
    echo -e "${C_INFO}║  WAF Deployment Wizard                     ║${C_RST}"
    echo -e "${C_INFO}║  Coraza + OWASP CRS v4                     ║${C_RST}"
    echo -e "${C_INFO}║  $APP_NAME $APP_VER                          ║${C_RST}"
    echo -e "${C_INFO}╚══════════════════════════════════════════╝${C_RST}"
    echo ""

    echo -e "${C_INFO}选择操作:${C_RST}"
    echo -e "  ${C_WARN}1.${C_RST} 安装 Coraza + CRS v4"
    echo -e "  ${C_WARN}2.${C_RST} 生成 Caddy + Coraza 配置"
    echo -e "  ${C_WARN}3.${C_RST} 生成 Nginx + Coraza 配置"
    echo -e "  ${C_WARN}4.${C_RST} 生成 HAProxy + Coraza 配置"
    echo -e "  ${C_WARN}5.${C_RST} 生成规则调优配置"
    echo -e "  ${C_WARN}6.${C_RST} 审计现有 WAF 配置 (只读)"
    echo -e "  ${C_WARN}0.${C_RST} 退出"
    echo ""
    local pick
    read -r -p "❯ 选择 [0-6]: " pick
    case $pick in
        1) install_coraza ;;
        2) generate_caddy_config ;;
        3) generate_nginx_config ;;
        4) generate_haproxy_config ;;
        5) generate_tuning_config ;;
        6) audit_waf || true ;;
        0) echo "退出"; exit 0 ;;
        *) echo -e "${C_FAIL}无效输入${C_RST}"; exit 1 ;;
    esac
}

# ── 主流程 ───────────────────────────────────────────────────
main() {
    parse_args "$@"

    case "$MODE" in
        install) install_coraza ;;
        caddy) generate_caddy_config ;;
        nginx) generate_nginx_config ;;
        haproxy) generate_haproxy_config ;;
        tune) generate_tuning_config ;;
        audit) audit_waf || true ;;
        interactive) interactive_mode || true ;;
        *) echo "未知模式: $MODE"; exit 1 ;;
    esac
    return 0
}

main "$@"
